services:
  frontend:
    build: .
    container_name: huoyan_frontend
    environment:
      BACKEND_HOST: ${BACKEND_HOST:-huoyan_backend}
      BACKEND_PORT: ${BACKEND_PORT:-8000}
    ports:
      - "3000:80"
    networks:
      - huoyan_net

networks:
  huoyan_net:
    external: true
    name: huoyan_net
